// ─────────────────────────────────────────────────────────────────────────────
// Gallery.jsx
// Interactive showcase gallery grid displaying generated AI imagery with filter tabs
// and prompt reveal hover overlays.
// ─────────────────────────────────────────────────────────────────────────────

import React, { useState } from 'react'
import { assets } from '../assets/assets'
import { motion } from 'framer-motion'

const galleryCategories = ['All', 'Characters', 'Product', 'Landscape', '3D']

const galleryItems = [
  {
    id: 1,
    title: 'Cyberpunk Ronin',
    prompt: 'A futuristic cyberpunk ronin standing in neon-lit Tokyo rain, 8k render, octane style',
    category: 'Characters',
    image: assets.sample_img_1,
  },
  {
    id: 2,
    title: 'Ethereal Forest Spirit',
    prompt: 'Ethereal forest spirit with bioluminescent antlers in a misty twilight woodland',
    category: 'Landscape',
    image: assets.sample_img_2,
  },
  {
    id: 3,
    title: 'Minimalist Perfume Mockup',
    prompt: 'Sleek luxury glass perfume bottle on frosted obsidian stone, volumetric lighting',
    category: 'Product',
    image: assets.sample_img_1,
  },
  {
    id: 4,
    title: '3D Isometric Floating Island',
    prompt: 'Low poly isometric floating island with waterfalls and ancient temples, blender 3d',
    category: '3D',
    image: assets.sample_img_2,
  },
  {
    id: 5,
    title: 'Neondream Mecha',
    prompt: 'Ornate mechanical armor suit with glowing cyan conduits, ultra detailed concept art',
    category: 'Characters',
    image: assets.sample_img_1,
  },
  {
    id: 6,
    title: 'Cosmic Nebula Vista',
    prompt: 'Deep space cosmic nebula with vibrant violet dust clouds and distant galaxies',
    category: 'Landscape',
    image: assets.sample_img_2,
  },
]

const Gallery = () => {
  const [activeCategory, setActiveCategory] = useState('All')

  const filteredItems = activeCategory === 'All'
    ? galleryItems
    : galleryItems.filter(item => item.category === activeCategory)

  return (
    <motion.section
      id="gallery"
      className="flex flex-col items-center justify-center my-28 px-4 max-w-6xl mx-auto"
      initial={{ opacity: 0, y: 40 }}
      transition={{ duration: 0.8 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
    >
      {/* Section Eyebrow Label */}
      <span className="text-xs font-mono tracking-widest uppercase text-cyan-400 bg-cyan-500/10 px-3.5 py-1 rounded-full border border-cyan-500/20 mb-3.5">
        SHOWCASE GALLERY
      </span>

      {/* Headline */}
      <h2 className="text-3xl sm:text-5xl font-bold tracking-tight text-white text-center mb-3">
        Rendered with Imagify.
      </h2>
      <p className="text-base sm:text-lg text-zinc-400 text-center max-w-xl mb-10">
        Browse community creations and inspect real prompts generated by our AI engine.
      </p>

      {/* Filter Tabs */}
      <div className="flex flex-wrap items-center justify-center gap-2 mb-12 bg-[#111114]/80 p-1.5 rounded-full border border-white/10 backdrop-blur-xl">
        {galleryCategories.map((cat) => (
          <button
            key={cat}
            onClick={() => setActiveCategory(cat)}
            className={`text-xs sm:text-sm font-medium px-4 py-2 rounded-full transition-all duration-300 ${
              activeCategory === cat
                ? 'bg-gradient-to-r from-violet-600 to-cyan-500 text-white shadow-lg shadow-violet-600/30 font-semibold'
                : 'text-zinc-400 hover:text-white hover:bg-white/5'
            }`}
          >
            {cat}
          </button>
        ))}
      </div>

      {/* Gallery Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5 w-full">
        {filteredItems.map((item) => (
          <div
            key={item.id}
            className="group relative rounded-2xl overflow-hidden border border-white/10 bg-[#161619] aspect-[4/3] shadow-xl hover:border-cyan-400/40 transition-all duration-500 hover:-translate-y-1"
          >
            {/* Gallery Image */}
            <img
              src={item.image}
              alt={item.title}
              className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700 ease-out"
            />

            {/* Category Tag Badge */}
            <div className="absolute top-3 left-3 bg-black/60 backdrop-blur-md px-3 py-1 rounded-full border border-white/10 text-[10px] font-mono text-zinc-300">
              {item.category}
            </div>

            {/* Prompt Hover Overlay */}
            <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/40 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex flex-col justify-end p-5 text-left">
              <h4 className="text-sm font-bold text-white mb-1">{item.title}</h4>
              <p className="text-xs font-mono text-zinc-300 line-clamp-2 leading-relaxed">
                "{item.prompt}"
              </p>
            </div>
          </div>
        ))}
      </div>
    </motion.section>
  )
}

export default Gallery
